#!/bin/bash
# Description:
#  Install web services and Nextcloud on CentOS (yum)
# TODO:
# 
# Version:
#  20181209 - First release

YOURIP=$(ip route get 8.8.8.8 2>/dev/null | awk '{print $NF; exit}')

function dev_tool()
{
        echo "Installing develop tools ..."
        sudo yum install -y git autoconf automake libtool screen
        sudo yum install -y epel-release yum-utils unzip curl wget bash-completion policycoreutils-python mlocate bzip2
}

function addCron()
{
        crontab -l > ${HOME}/ctab
        tmark=$(date +%Y%m%d%H%M%S)
        echo "#At ${tmark} added" >> ${HOME}/ctab
        sed -i "s/\#At ${tmark} added/\#At ${tmark} added\n ${1//\//\\/}/g" ${HOME}/ctab
        crontab ${HOME}/ctab
        rm ${HOME}/ctab
}

function insApache()
{
	echo "Now installing Apache2 service ..."
	sudo yum install -y httpd
	sudo systemctl enable httpd
	sudo systemctl start httpd
	echo "Open http://${YOURIP}/ to verify Apache service"
}

function insDatabase()
{
	echo "Now installing Database service ..."
	sudo yum install -y mariadb mariadb-server sqlite
	sudo systemctl enable mariadb
	sudo systemctl start mariadb
	echo "Finishing MySQL secure setting ..."
	sudo mysql_secure_installation
	echo "Now you have MariaDB(MySQL) and sqlite support on your system"
}

function insPHP()
{
	echo "Now installing PHP7 service ..."
	sudo yum install -y centos-release-scl
	sudo yum install -y rh-php72 rh-php72-php rh-php72-php-gd rh-php72-php-mbstring rh-php72-php-mysqlnd rh-php72-php-ldap
	sudo yum install -y rh-php72-php-opcache rh-php72-php-pecl-apcu rh-php72-php-intl rh-php72-php-pecl-redis
	echo -e "<?php\nphpinfo();\n?>" > ${HOME}/info.php
	sudo mv /etc/httpd/conf.d/php.conf /etc/httpd/conf.d/php54.off
	sudo mv /etc/httpd/conf.modules.d/10-php.conf /etc/httpd/conf.modules.d/10-php54.off
	sudo ln -s /opt/rh/httpd24/root/etc/httpd/conf.d/rh-php72-php.conf /etc/httpd/conf.d/
	sudo ln -s /opt/rh/httpd24/root/etc/httpd/conf.modules.d/15-rh-php72-php.conf /etc/httpd/conf.modules.d/
	sudo ln -s /opt/rh/httpd24/root/etc/httpd/modules/librh-php72-php7.so /etc/httpd/modules/
	sudo systemctl restart httpd
	if [ -d /var/www/html/ ]; then
		sudo cp ${HOME}/info.php /var/www/html/
		echo "Open http://${YOURIP}/info.php to verify PHP Version"
	else
		echo "Can't locate your web root, please copy ${HOME}/info.php to your web root to verify PHP Version"
	fi
}

function insPMA()
{
	echo "Now installing phpMyAdmin service ..."
	sudo yum install -y phpmyadmin
	sudo sed -i "s/127.0.0.1/127.0.0.1 ${YOURIP}/g" /etc/httpd/conf.d/phpMyAdmin.conf
	sudo systemctl restart httpd
	echo "Open http://${YOURIP}/phpMyAdmin/ to verify phpMyAdmin Version"
}

function insWeb()
{
	insApache
	insDatabase
	insPHP
	insPMA
}

function insNextcloud()
{
	echo "Now installing Nextcloud service ..."
	read -n 1 -p "Do you have installed Apache, MySQL/sqlite and PHP?[Yes/no]" i
	case ${i} in
		n|N)
		return 1
		;;
		*)
		;;
	esac
	cd
	wget https://download.nextcloud.com/server/releases/nextcloud-14.0.4.tar.bz2
	if [ ${?} -gt 0 ]; then
		echo "Error downloading package, please goto https://nextcloud.com/install/ to download proper package."
		return 2
	fi
	tar -jxvf nextcloud-14.0.4.tar.bz2
	if [ ${?} -gt 0 ]; then
		echo "Decompress failed! Please download and decompress again."
		return 3
	fi
	if [ ! -d /var/www/ ]; then
		echo "Can't find your web root!"
		return 4
	fi
	sudo mv nextcloud /var/www/
	sudo mkdir /var/www/nextcloud/data
	sudo chown -R apache.apache /var/www/nextcloud

	echo "Alias /nextcloud \"/var/www/nextcloud/\"" > ${HOME}/nextcloud.conf
	echo "  <Directory /var/www/nextcloud/>" >> ${HOME}/nextcloud.conf
	echo "    Options FollowSymlinks MultiViews" >> ${HOME}/nextcloud.conf
	echo "    AllowOverride All" >> ${HOME}/nextcloud.conf
	echo "   <IfModule mod_dav.c>" >> ${HOME}/nextcloud.conf
	echo "    Dav off" >> ${HOME}/nextcloud.conf
	echo "   </IfModule>" >> ${HOME}/nextcloud.conf
	echo "  </Directory>" >> ${HOME}/nextcloud.conf
	sudo mv ${HOME}/nextcloud.conf /etc/httpd/conf.d/
	sudo restorecon -R /etc/httpd/conf.d/

	sudo semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/data(/.*)?'
	sudo semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/config(/.*)?'
	sudo semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/apps(/.*)?'
	sudo semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/.htaccess'
	sudo semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/.user.ini'
	sudo semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/3rdparty/aws/aws-sdk-php/src/data/logs(/.*)?'
	sudo restorecon -R '/var/www/nextcloud/'
	sudo setsebool -P httpd_can_network_connect on

	sudo systemctl restart httpd
	echo "Now you should:"
	echo "1, Open http://${YOURIP}/phpmyadmin/ to setup database for Nextcloud"
	echo "2, Open http://${YOURIP}/nextcloud/ to configure your Nextcloud service" i
	read -n 1 -p "Press any key to finish." i
}

function insSSL()
{
	echo "Now installing SSL certificate service ..."
	echo "You must have Apache service installed first, and your domain name works properly."
	echo "Otherwise you wouldn't get the certificate but will ruin your Apache service."
	read -n 1 -p "Continue?[yes/No]" i
	case ${i} in
		y|Y)
		;;
		*)
		return 1
		;;
	esac
	cd
	sudo yum install -y mod_ssl openssl
	cp /etc/httpd/conf.d/ssl.conf ssl.conf.bak
	wget https://dl.eff.org/certbot-auto
	sudo chmod a+x certbot-auto
	sudo mv certbot-auto /usr/local/bin/
	/usr/local/bin/certbot-auto certonly --webroot -w /var/www/html -d ${1}
	sudo sed -i "s/SSLCertificateFile[[:space:]]\/.*/SSLCertificateFile  \/etc\/letsencrypt\/live\/${1}\/fullchain.pem/g" /etc/httpd/conf.d/ssl.conf
	sudo sed -i "s/SSLCertificateKeyFile[[:space:]]\/.*/SSLCertificateKeyFile  \/etc\/letsencrypt\/live\/${1}\/privkey.pem/g" /etc/httpd/conf.d/ssl.conf
	sudo systemctl restart httpd
	addCron '# * 3 * * 0 /usr/local/bin/certbot-auto renew --quiet --post-hook "sudo systemctl restart httpd"'
}

function usage()
{
	echo "Highly recommend set your sudo NOPASSWD via visudo!"
	echo "${0} [ devtool | web | nextcloud ]"
	echo "${0} ssl domainname"
}

case ${1} in
	'devtool')
	dev_tool ;;
	'apache')
	insApache ;;
	'mysql')
	insDatabase ;;
	'php')
	insPHP ;;
	'pma')
	insPMA ;;
	'web')
	insWeb ;;
	'nextcloud')
	insNextcloud ;;
	'ssl')
	insSSL ${2} ;;
	*)
	usage ;;
esac

exit 0
